# Generated by Django 4.2.27 on 2026-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars",
                        verbose_name="аватар",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="о себе")),
                (
                    "pseudonym",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="псевдоним"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата и время обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "профили",
                "ordering": ["-created_at"],
            },
        ),
    ]
