# Generated by Django 6.0 on 2026-01-03 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение для вашего аватара",
                null=True,
                upload_to="avatars/%Y/&m/&d/",
                verbose_name="аватар",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Расскажите о себе (максимум 500 символов).",
                max_length=500,
                verbose_name="Биография",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на ваш веб-сайт или блог.",
                verbose_name="Веб-сайт",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7ec6d5e5-ef8a-44c3-ab9c-908950b3d1e5"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "Пользователь с таким именем уже существует."
                },
                help_text="Обязательное поле 150 символов. Только буквы, цифры и @/./_/+/-_.",
                max_length=150,
                unique=True,
                verbose_name="имя пользователя",
            ),
        ),
    ]
