# Generated by Django 6.0 on 2026-01-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poem",
            old_name="context",
            new_name="content",
        ),
    ]
