# Generated by Django 4.2.27 on 2026-01-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poem", "0002_rename_context_poem_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
    ]
