# Generated by Django 5.2.8 on 2025-12-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="pseudonym",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="псевдоним"
            ),
        ),
    ]
